version: '3'
services:

  user-mysql:
     image: mysql:5.7
     network_mode: host
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: password
       MYSQL_PASSWORD: password
       MYSQL_DATABASE: DockerStudentDB
       MYSQL_HOST: localhost
  user-mongo:
     image: mongo
     network_mode: host
     ports:
       - "27017:27017"
     environment:
       MONGO_DATABASE: DepartmentDB
       MONGO_PORT: 27017
       MONGO_HOST: localhost

  webapp3-service:
     image: webapp3-service
     build: 
       context: webapp3/
     depends_on:
       - user-mysql
     ports:
       - "8089:8089"
     network_mode: host
     restart: always
  webapp4:
     image: webapp4-service
     build: 
       context: webapp4/
     depends_on:
       - user-mongo
     ports:
       - "8083:8083"
     network_mode: host
     restart: always
       

